name: Image2GPS
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch=2.1.*
  - torchvision=0.16.*
  - torchaudio=2.1.*
  - pytorch-cuda=12.1
  - numpy=1.26.*
  - pandas=2.1.*
  - scikit-learn
  - scipy
  - requests
  - pyyaml
  - ipykernel
  - pip:
      - pytorch-lightning==2.1.2
      - torchmetrics==1.2.0
      - pytorch-metric-learning==2.3.0
      - tqdm==4.67.1
      - prettytable==3.9.0
      - faiss-cpu==1.13.2
      - aiohttp==3.13.2
