name: image2gps
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch::pytorch==2.2.0        # Updated
  - pytorch::pytorch-cuda=12.1
  - pytorch::torchvision==0.17.0   # Updated to match 2.2.0
  - pip
  - pip:
      - xformers==0.0.24  
      - pandas==2.1.3
      - prettytable==3.9.0
      - pytorch-lightning==2.1.2
      - pytorch-metric-learning==2.3.0
      - torchmetrics==1.2.0
      - Pillow